#!/usr/bin/env bash
# domain info
# shellcheck disable=SC2086
if [ "$#" -eq 1 ]
then
    dig www."$1" | grep -A1 'ANSWER SECTION' | grep -e www | awk '{print "The subdomain www is a " $4 " record and points to " $5}'
    dig lb-01."$1" | grep -A1 'ANSWER SECTION' | grep -e lb-01 | awk '{print "The subdomain lb-01 is a " $4 " record and points to " $5}'
    dig web-01."$1" | grep -A1 'ANSWER SECTION' | grep -e web-01 | awk '{print "The subdomain web-01 is a " $4 " record and points to " $5}'
    dig web-02."$1" | grep -A1 'ANSWER SECTION' | grep -e web-02 | awk '{print "The subdomain web-02 is a " $4 " record and points to " $5}'
fi
