#!/usr/bin/env bash
# Makes web 2 same as web 1

sudo apt-get update
sudo apt-get -y install nginx
sudo sed -i "15i \add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
