#!/usr/bin/env bash
# install load balancer

sudo apt-get update
sudo apt-get -y install haproxy
sudo sed -i '$a ENABLED=1' /etc/default/haproxy
sudo sed -i "\$ a\listen appname 0.0.0.0:80\n\tmode http\n\tbalance roundrobin\n\tserver 251-web-01 52.91.246.129:80 check\n\tserver 251-web-02 107.23.155.217:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy restart 
