#!/usr/bin/env bash
#debugs server with help from stackoverflow
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
