#!/usr/bin/env bash
#redirect

sudo apt-get update
sudo apt-get -y install nginx
sudo sed -i "30i rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent" /etc/nginx/sites-available/default
sudo service nginx restart
