#!/usr/bin/env bash
#redirect

sudo apt-get update
sudo apt-get -y install nginx
sudo sed -i "30i \\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
sed -i "43i error_page 404 /404.html; location = /404.html { root /usr/share/nginx/html; internal; }"
sudo service nginx restart
